//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARSHOP_12
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Carshop12Entities : DbContext
    {
        public Carshop12Entities()
            : base("name=Carshop12Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbleAdmin> tbleAdmins { get; set; }
    
        public virtual int DeleteAdmin(Nullable<int> aDMINID)
        {
            var aDMINIDParameter = aDMINID.HasValue ?
                new ObjectParameter("ADMINID", aDMINID) :
                new ObjectParameter("ADMINID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAdmin", aDMINIDParameter);
        }
    
        public virtual ObjectResult<DoAdminLogin_Result> DoAdminLogin(string eMAIL, string pASSWORD)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoAdminLogin_Result>("DoAdminLogin", eMAILParameter, pASSWORDParameter);
        }
    
        public virtual ObjectResult<GetAdmins_Result> GetAdmins()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAdmins_Result>("GetAdmins");
        }
    }
}
