//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARSHOP_12
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Carshop12Entities : DbContext
    {
        public Carshop12Entities()
            : base("name=Carshop12Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbleAdmin> tbleAdmins { get; set; }
        public virtual DbSet<tbleBrand> tbleBrands { get; set; }
        public virtual DbSet<tbleCar> tbleCars { get; set; }
        public virtual DbSet<tbleCarName> tbleCarNames { get; set; }
        public virtual DbSet<tbleType> tbleTypes { get; set; }
    
        public virtual int DeletBrand(Nullable<int> brandId)
        {
            var brandIdParameter = brandId.HasValue ?
                new ObjectParameter("BrandId", brandId) :
                new ObjectParameter("BrandId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeletBrand", brandIdParameter);
        }
    
        public virtual int DeleteAdmin(Nullable<int> aDMINID)
        {
            var aDMINIDParameter = aDMINID.HasValue ?
                new ObjectParameter("ADMINID", aDMINID) :
                new ObjectParameter("ADMINID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAdmin", aDMINIDParameter);
        }
    
        public virtual int DeleteCars(Nullable<int> carID)
        {
            var carIDParameter = carID.HasValue ?
                new ObjectParameter("CarID", carID) :
                new ObjectParameter("CarID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCars", carIDParameter);
        }
    
        public virtual int DeleteType(Nullable<int> typeID)
        {
            var typeIDParameter = typeID.HasValue ?
                new ObjectParameter("TypeID", typeID) :
                new ObjectParameter("TypeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteType", typeIDParameter);
        }
    
        public virtual ObjectResult<DoAdminLogin_Result> DoAdminLogin(string eMAIL, string pASSWORD)
        {
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var pASSWORDParameter = pASSWORD != null ?
                new ObjectParameter("PASSWORD", pASSWORD) :
                new ObjectParameter("PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoAdminLogin_Result>("DoAdminLogin", eMAILParameter, pASSWORDParameter);
        }
    
        public virtual ObjectResult<GetAdmins_Result> GetAdmins()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAdmins_Result>("GetAdmins");
        }
    
        public virtual ObjectResult<GetBrand_Result> GetBrand()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBrand_Result>("GetBrand");
        }
    
        public virtual ObjectResult<GetCarNames_Result> GetCarNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCarNames_Result>("GetCarNames");
        }
    
        public virtual ObjectResult<GetCars_Result> GetCars()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCars_Result>("GetCars");
        }
    
        public virtual ObjectResult<GetType_Result> GetType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetType_Result>("GetType");
        }
    }
}
