//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CARSHOP_12
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbleCar
    {
        public int CarID { get; set; }
        public string Name { get; set; }
        public Nullable<int> BrandId { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public string Transmission { get; set; }
        public string Entertainment { get; set; }
        public string Seats { get; set; }
        public string GpsTracker { get; set; }
        public string Steering { get; set; }
        public string Headlights { get; set; }
        public string HvAC { get; set; }
        public string Safety { get; set; }
        public string Fuel { get; set; }
        public string Instrument { get; set; }
    
        public virtual tbleBrand tbleBrand { get; set; }
        public virtual tbleType tbleType { get; set; }
    }
}
